services:
    database:
        image: postgres:latest
        ports:
            -   5432:5432
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: default
        volumes:
            -   ./database/:/var/lib/postgresql/data/